version: 0.1.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
#assembly_info:
#  patch: true
#  file: '**\AssemblyInfo.*'
#  assembly_version: '{version}'
#  assembly_file_version: '{version}'
#  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

environment:
  MYGET_KEY:
    secure: b+lrnLDBMVds0RmnoyuVqVYz5sjgqSeY/AhWn+iTT7/+jaa4VaHihRpFaHWRs8AN
  NUGET_KEY:
    secure: GWychdaWwFZJHzYsFL1es67HqNEgirgT3iHeewQmNSFODWFEUzn4Eu5QT1XH5C8/
before_build:
- cmd: nuget restore
#after_build:
#- cmd: dotnet pack -c Release src/SigStat.Common/SigStat.Common.csproj
build:
  publish_nuget: true
  verbosity: normal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/bencekovari/api/v2/package
  api_key:
    secure: Lt06yKCteORxJGN1HKZz3WbzQXLDHsRiuJCXTVKOM9DAAC7ZR/Lr9OI4BsOHrguh

test_script:
- OpenCover.Console.exe -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test \"test\SigStat.Common.Test\" --configuration Release" -filter:"+[SigStat.Common*]* -[SigStat.Common.Test*]*" -oldStyle -register:user
- codecov -f "results.xml"