version: 0.1.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
#assembly_info:
#  patch: true
#  file: '**\AssemblyInfo.*'
#  assembly_version: '{version}'
#  assembly_file_version: '{version}'
#  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

environment:
  #access_token:
   # secure: NuXJPvfbtEJEsj358sMDapkR5DWHUt46ftc5sHll0zQkLMhc/N7zVGpLYZc0wCPC
  MYGET_KEY:
    secure: b+lrnLDBMVds0RmnoyuVqVYz5sjgqSeY/AhWn+iTT7/+jaa4VaHihRpFaHWRs8AN
  NUGET_KEY:
    secure: GWychdaWwFZJHzYsFL1es67HqNEgirgT3iHeewQmNSFODWFEUzn4Eu5QT1XH5C8/
  
#skip_commits:  
#   message: /PDF/   

before_build:
- cmd: nuget restore
- choco install opencover.portable
- choco install codecov
#- ps: Install-Product node 6
#- npm install -g github-wikito-converter
#- npm install -g html-pdf
#after_build:
#- cmd: dotnet pack -c Release src/SigStat.Common/SigStat.Common.csproj
build:
  publish_nuget: true
  project: /src/SigStat.Common
  verbosity: normal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/bencekovari/api/v2/package
  api_key:
   secure: Lt06yKCteORxJGN1HKZz3WbzQXLDHsRiuJCXTVKOM9DAAC7ZR/Lr9OI4BsOHrguh

test_script:
- OpenCover.Console.exe -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test \"test\SigStat.Common.Test\" --configuration Release" -filter:"+[SigStat.Common*]* -[SigStat.Common.Test*]*" -oldStyle -register:user
- codecov -f "results.xml" -r "sigstat/sigstat"

on_success:
- git config --global credential.helper store
- ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- git config --global user.email "hargitomi97@gmail.com"
- git config --global user.name "hargitomi97"
- md C:\projects\wiki
- cd C:\projects\wiki
- git clone https://github.com/sigstat/sigstat.wiki.git
- C:\projects\sigstat\docs\generator\MarkdownGenerator.exe C:\projects\sigstat\src\SigStat.Common\bin\Release\netstandard2.0\SigStat.Common.dll "C:\projects\wiki\SigStat.wiki"
#- echo All | xcopy C:\projects\sigstat\docs\md\_Sidebar.md C:\projects\wiki\SigStat.wiki
- cd C:\projects\wiki\SigStat.wiki
- git add -A
- git diff-index --quiet HEAD || git commit -am "wiki"
- git push
#- cd C:\projects\sigstat\docs
#- gwtc C:\projects\wiki\SigStat.wiki
#- html-pdf documentation.html documentation.pdf
#- rm documentation.html
#- git add .
#- git diff-index --quiet HEAD || git commit -am "PDF"
#- git push
